language: python

sudo: required
dist: trusty

python:
  - 2.7

services:
  - docker

install:
  - docker build -f Dockerfile -t mottosso/pyglet .

script:
  - docker run --rm -v $(pwd):/workspace mottosso/pyglet
